### ISSUE TITLE
Tracking issue: Search queries

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/aleph#2889]
This issue tracks multiple issues related to relevance/precision, search query interpretation etc.:

- [ ] https://github.com/alephdata/aleph/issues/2888
- [ ] https://github.com/alephdata/aleph/issues/2023
- [ ] https://github.com/alephdata/aleph/issues/2834
- [ ] https://github.com/alephdata/aleph/issues/2500
