### ISSUE TITLE
[META] Aleph 2.0 - what needs to be done.

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#333]
So we're getting really close. I'll list tickets that should be resolved here and also do an overview of small items that we can keep of a running tally of loose ends: 

* #321 - Re-organize components and screens in the React app
* #323 - There are two collection info renderers
* #327 - [And more generally a refactor of the CollectionsBrowser ] 
* #319 - Search UI overhaul 
* #330 - Folders/document viewer detail fixes
* #320 - Create alert button on search results
* #325 - Work out some improvements for the collections UI
* #314 - Paginated results for relationships
* Need ticket: folder view in documents refactor
* Are we going to give search result previews a stab or no?
* Are we going to do tabular filters? (i.e. records search)
* Are we going to do PDF search? (i.e. records search)

And small items, which we may want to branch out into proper issues if they become complex:

* [ ] Put aleph version in API metadata and show in the footer
* [ ] Make the docker pipeline generated tagged builds
* [ ] Re-vamp the home page layout
* [ ] Make collections browser items a list and get rid of CollectionCard
* [ ] Error handling for errors 404 
* [ ] Error handling for errors 401 (show login link) 
* [ ] Update collections in ES index version in more cases (every hour?)

**Comment by pudo** [comment]
Decisions from the team meeting this Friday:

1. We'll do preview on search
   * Small-width sidebar previews for metadata
   * Wide previews for document content or entity relationships
   * Toolbar on top of preview: close, open, expand/collapse wide preview
2. Collections are a sidebar
   * They are edited as a modal
   * Access control is a sidebar tab
   * Folder view is a sidebar tab
   * Schema breakdown in metadata overview
3. Profile: a double modal 
4. Entities
   * Preview shows properties
   * Expanded preview shows relationships with other entities 
   * Content view is tabbed by relationship type
5. We have a link to collection index in the top navbar
6. We get rid of CollectionScreen, CollectionBrowser.
